### ISSUE TITLE
Convert CSV To YAM

### ISSUE THREAD

**Issue by tpphu** [tpphu/golang-training#14]
Cho các bạn một [file](https://github.com/tpphu/golang-trainning/blob/master/data/list-regions.csv), mô tả cấu trúc **tỉnh thành**,**quận huyện**,**phường xã** như bên dưới
```csv
RegionId,RegionName,DistrictId,DistrictName,WardId,WardName
1,Hồ Chí Minh,1,Quận 1,26734,Phường Tân Định
1,Hồ Chí Minh,1,Quận 1,26737,Phường Đa Kao
1,Hồ Chí Minh,1,Quận 1,26740,Phường Bến Nghé
1,Hồ Chí Minh,1,Quận 1,26743,Phường Bến Thành
1,Hồ Chí Minh,1,Quận 1,26746,Phường Nguyễn Thái Bình
1,Hồ Chí Minh,1,Quận 1,26749,Phường Phạm Ngũ Lão
1,Hồ Chí Minh,1,Quận 1,26752,Phường Cầu Ông Lãnh
1,Hồ Chí Minh,1,Quận 1,26755,Phường Cô Giang
```
Hãy chuyển sang file yaml với format như sau:

```yaml
- id: 1
  name: Hồ Chí Minh
  districts:
  - id: 1
    name: Quận 1
    wards:
    - id: 26734
      name: Phường Tân Định
    - id: 26737
      name: Phường Đa Kao
    - id: 26740
      name: Phường Bến Nghé
    - id: 26743
      name: Phường Bến Thành
    - id: 26746
      name: Phường Nguyễn Thái Bình
    - id: 26749
      name: Phường Phạm Ngũ Lão
    - id: 26752
      name: Phường Cầu Ông Lãnh
    - id: 26755
      name: Phường Cô Giang
```
